# Generated by Django 3.1.4 on 2021-01-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerepo', '0002_auto_20210116_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
