# Generated by Django 3.1.4 on 2021-01-17 19:12

from django.db import migrations, models
import imagerepo.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerepo', '0003_image_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=imagerepo.models.upload_to, verbose_name='Image'),
        ),
    ]
